#ifndef ARKANOIDWITHOUTANENGINE_SRC_GAME_PHYSICS_COLLISION_DATA_HPP_
#define ARKANOIDWITHOUTANENGINE_SRC_GAME_PHYSICS_COLLISION_DATA_HPP_

namespace arkanoid
{
struct CollisionData
{
    // data...
};
}

#endif
